  development:
    adapter: postgresql
    encoding: utf8
    database: demo_Store
    username: root
    password: root
    host: localhost

  staging:
    adapter: postgresql
    encoding: utf8
    database: demo_Store
    username: root
    password: root
    host: localhost


  production:
    adapter: postgresql
    encoding: utf8
    database: demo_Store
    username: root
    password: root
    host: localhost
